############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
# Passes on URLError, timeout, and BadStatusLine exceptions.
#     See: 
#     http://docs.python.org/2/library/urllib2.html
#     http://docs.python.org/2/library/httplib.html
#
############################################################

try:
    import json
except ImportError:
    import sys
    sys.path.append('simplejson-2.3.3')
    import simplejson as json
    
import urllib2, httplib, urlparse
from urllib2 import URLError, HTTPError

_CT = 'content-type'
_AJ = 'application/json'
_URL_SCHEME = frozenset(['http', 'https']) 

class ServerError(Exception):

    def __init__(self, name, code, message):
        self.name = name
        self.code = code
        self.message = message

    def __str__(self):
        return self.name + ': ' + str(self.code) + '. ' + self.message

class Genotype_PhenotypeAPI:

    def __init__(self, url, timeout = 30 * 60):
        if url is None:
            raise ValueError('A url is required')
        scheme, _, _, _, _, _ = urlparse.urlparse(url)
        if scheme not in _URL_SCHEME:
            raise ValueError(url + " isn't a valid http url")
        self.url = url
        self.timeout = int(timeout)
        if self.timeout < 1:
            raise ValueError('Timeout value must be at least 1 second')

    def get_experiments(self, kb_genome):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.get_experiments',
                     'params': [kb_genome],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def get_traits(self, kb_study_experiment):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.get_traits',
                     'params': [kb_study_experiment],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def traits_to_variations(self, trait, pvaluecutoff):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.traits_to_variations',
                     'params': [trait, pvaluecutoff],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def chromosome_position_from_variation_details(self, variation_details):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.chromosome_position_from_variation_details',
                     'params': [variation_details],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def traits_to_genes(self, trait, pvaluecutoff, distance):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.traits_to_genes',
                     'params': [trait, pvaluecutoff, distance],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def variations_to_genes(self, chromosomal_positions, distance):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.variations_to_genes',
                     'params': [chromosomal_positions, distance],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def find_common_snps(self, trait_list_pvalue):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.find_common_snps',
                     'params': [trait_list_pvalue],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def selected_locations_to_genes(self, trait, pmin, pmax, chromosomal_locations, distance):

        arg_hash = { 'method': 'Genotype_PhenotypeAPI.selected_locations_to_genes',
                     'params': [trait, pmin, pmax, chromosomal_locations, distance],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')




        
