############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
# Passes on URLError, timeout, and BadStatusLine exceptions.
#     See: 
#     http://docs.python.org/2/library/urllib2.html
#     http://docs.python.org/2/library/httplib.html
#
############################################################

try:
    import json
except ImportError:
    import sys
    sys.path.append('simplejson-2.3.3')
    import simplejson as json
    
import urllib2, httplib, urlparse
from urllib2 import URLError, HTTPError

_CT = 'content-type'
_AJ = 'application/json'
_URL_SCHEME = frozenset(['http', 'https']) 

class ServerError(Exception):

    def __init__(self, name, code, message):
        self.name = name
        self.code = code
        self.message = message

    def __str__(self):
        return self.name + ': ' + str(self.code) + '. ' + self.message

class KBaseNetworks:

    def __init__(self, url, timeout = 30 * 60):
        if url is None:
            raise ValueError('A url is required')
        scheme, _, _, _, _, _ = urlparse.urlparse(url)
        if scheme not in _URL_SCHEME:
            raise ValueError(url + " isn't a valid http url")
        self.url = url
        self.timeout = int(timeout)
        if self.timeout < 1:
            raise ValueError('Timeout value must be at least 1 second')

    def allDatasets(self, ):

        arg_hash = { 'method': 'KBaseNetworks.allDatasets',
                     'params': [],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def allDatasetSources(self, ):

        arg_hash = { 'method': 'KBaseNetworks.allDatasetSources',
                     'params': [],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def allNetworkTypes(self, ):

        arg_hash = { 'method': 'KBaseNetworks.allNetworkTypes',
                     'params': [],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def datasetSource2Datasets(self, datasetSourceRef):

        arg_hash = { 'method': 'KBaseNetworks.datasetSource2Datasets',
                     'params': [datasetSourceRef],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def taxon2Datasets(self, taxon):

        arg_hash = { 'method': 'KBaseNetworks.taxon2Datasets',
                     'params': [taxon],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def networkType2Datasets(self, networkType):

        arg_hash = { 'method': 'KBaseNetworks.networkType2Datasets',
                     'params': [networkType],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def entity2Datasets(self, entityId):

        arg_hash = { 'method': 'KBaseNetworks.entity2Datasets',
                     'params': [entityId],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def buildFirstNeighborNetwork(self, datasetIds, entityIds, edgeTypes):

        arg_hash = { 'method': 'KBaseNetworks.buildFirstNeighborNetwork',
                     'params': [datasetIds, entityIds, edgeTypes],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def buildFirstNeighborNetworkLimtedByStrength(self, datasetIds, entityIds, edgeTypes, cutOff):

        arg_hash = { 'method': 'KBaseNetworks.buildFirstNeighborNetworkLimtedByStrength',
                     'params': [datasetIds, entityIds, edgeTypes, cutOff],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def buildInternalNetwork(self, datasetIds, geneIds, edgeTypes):

        arg_hash = { 'method': 'KBaseNetworks.buildInternalNetwork',
                     'params': [datasetIds, geneIds, edgeTypes],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')

    def buildInternalNetworkLimitedByStrength(self, datasetIds, geneIds, edgeTypes, cutOff):

        arg_hash = { 'method': 'KBaseNetworks.buildInternalNetworkLimitedByStrength',
                     'params': [datasetIds, geneIds, edgeTypes, cutOff],
                     'version': '1.1'
                     }

        body = json.dumps(arg_hash)
        try:
            ret = urllib2.urlopen(self.url, body, timeout = self.timeout)
        except HTTPError as h:
            if _CT in h.headers and h.headers[_CT] == _AJ:
        		    err = json.loads(h.read()) 
        		    if 'error' in err:
        			     raise ServerError(**err['error'])
        		    else: 			   #this should never happen... if it does 
        			     raise h     #  h.read() will return '' in the calling code.
            else:
        		    raise h
        if ret.code != httplib.OK:
            raise URLError('Received bad response code from server:' + ret.code)
        resp = json.loads(ret.read())

        if 'result' in resp:
            return resp['result'][0]
        else:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')




        
