options(repos = c(CRAN = "http://cran.r-project.org/"))

install.packages("devtools")
install.packages("fACD", repos="http://R-Forge.R-project.org")  # ACD model
install.packages("Rglpk", type="source")
install.packages("Quandl", type="source")
install.packages("pkgconfig")
install.packages("knitr")
install.packages("plyr")

install.packages("pkgconfig")
install.packages("knitr")
install.packages("plyr")
install.packages("stringr")
install.packages("rgl")
install.packages("data.table")
install.packages("ggplot2")
install.packages("lme4")
install.packages("reshape")
install.packages("RColorBrewer")
install.packages("gplots")
install.packages("png")
install.packages("lattice")
install.packages("tm")
install.packages("igraph")
install.packages("RJSONIO")
install.packages("curl")
install.packages("devtools")
install.packages("wordcloud")
install.packages("timeSeries", repos="http://R-Forge.R-project.org")
install.packages("amap")
install.packages("pheatmap")
install.packages("googleVis")
install.packages("tiff")

require(devtools)
devtools::install_github("ramnathv/rCharts")
#source("http://bioconductor.org/biocLite.R")
#biocLite()
