version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: monthly
    time: '11:00'
  groups:
    python-dependencies:
      patterns:
        - "*"
  open-pull-requests-limit: 20
  ignore:
    - dependency-name: "notebook"
      versions: '>= 7.0.0'
- package-ecosystem: pip
  directory: "/docker_image_dependencies"
  schedule:
    interval: monthly
    time: '11:00'
  groups:
    docker-image-python-deps:
      patterns:
        "*"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: '11:00'
  groups:
    npm-dependencies:
      patterns:
        "*"
  open-pull-requests-limit: 20
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: '11:00'
  open-pull-requests-limit: 20
