version: 2
updates:
- package-ecosystem: "pip"
  directory: "/src"
  schedule:
    interval: "monthly"
  groups:
    pip:
      patterns:
        - "*"
  open-pull-requests-limit: 20
  ignore:
    - dependency-name: "notebook"
      versions: ">= 7.0.0"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    npm:
      patterns:
        - "*"
  open-pull-requests-limit: 20
  ignore:
    - dependency-name: "bootstrap"
    - dependency-name: "bowser"
    - dependency-name: "d3"
    - dependency-name: "jquery"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directory: "/.github"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
