env:
  browser: true
  amd: true
extends: 'eslint:recommended'
parserOptions:
    ecmaVersion: 5
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
    - allow:
      - warn
      - error
