env:
  amd: true
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - prettier
parserOptions:
    ecmaVersion: 2018
root: true
rules:
  strict:
    - error
    - function
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
    - allow:
      - warn
      - error
  require-await:
    - error
