#!/usr/bin/env python
"""
Update narrative/src/config.json to contain a git hash and timestamp of the
commit from which we're deploying.

Updated 1/31/2015
"""

from __future__ import print_function
import json
import os
import subprocess
import sys
import argparse
import re
__author__ = 'Bill Riehl <wjriehl@lbl.gov>'
default_cfg_file = 'config.json.templ'

def main(args):
    try:
        if args.vb > 0:
            print("Opening config file")
        cfg_text = open(args.cfg_file).read()

        if args.vb > 0:
            print("Getting git commit info")
        hash_time = subprocess.check_output('git log --pretty="%h,%ad" -n 1', shell=True)
        hash_time = hash_time.decode('utf-8').strip().split(',')

        # Not a fan of regexes, but this skips having to parse bits of template as JSON
        cfg_text = re.sub(r'"git_commit_hash":\s*.*,', '"git_commit_hash": "{}",'.format(hash_time[0]), cfg_text)
        cfg_text = re.sub(r'"git_commit_time":\s*.*,', '"git_commit_time": "{}",'.format(hash_time[1]), cfg_text)

        args.env = args.env.lower()
        if args.vb > 0:
            print("Checking valid environment '" + args.env + "'")
        if (args.env not in ['ci', 'next', 'prod', 'appdev']):
            raise Exception('Unknown environment: "' + args.env + '"\nAllowed environments: ci, next, prod, appdev')

        if args.vb > 0:
            print("WARNING: IGNORING environment setting of " + args.env + "! Environment set via runtime env var CONFIG_ENV")
            print("WARNING: IGNORING dev_mode setting! This is now set based on the environment at load time.")

        if args.vb > 0:
            print("Writing updated config file")
        outfile = open(args.cfg_file, 'w')
        outfile.write(cfg_text)
        outfile.close()

        if args.opt_out is not None:
            if args.vb > 0:
                print("Writing updated version check file for browser access")
            mini_cfg = {
                'version' : re.search(r'"version":\s*"(.*)"', cfg_text).groups()[0],
                'git_hash' : hash_time[0]
            }
            outfile = open(args.opt_out, 'w')
            outfile.write(json.dumps(mini_cfg, separators=(',',':')))
            outfile.close()

    except Exception as err:
        print("Failed to update git commit hash and timestamp!")
        print(err)
        raise

def parse_args():
    p = argparse.ArgumentParser(description=__doc__.strip())
    p.add_argument("-f", "--config-file", dest="cfg_file", default=default_cfg_file, help="JSON config file (default=%(default)s)")
    p.add_argument("-v", "--verbose", dest="vb", action="count", default=0, help="Increase verbosity")
    p.add_argument("-o", "--output", dest="opt_out", default=None, help="Optional extra output file for Narrative version and git stamp")
    p.add_argument("-e", "--env", dest="env", default="ci", help="Configure KBase environment. Choose from ci, next, prod, appdev (default=%(default)s)")
    p.add_argument("-d", "--dev-mode", dest="dev_mode", default="true", help="Set developer mode as either 'true' or 'false' (default=true)")
    return p.parse_args()

if __name__ == '__main__':
    sys.exit(main(parse_args()))