---
name: Build Prod RC Image
on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize
    - ready_for_review

jobs:
  run_build_and_push:
    uses: ./.github/workflows/build_and_push_image.yml

  run_unit_tests:
    uses: ./.github/workflows/unit_test.yml
    needs: run_build_and_push
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
